version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge